name: Publish packages to npmjs.com
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish example-circular-dependencies-2-marco
        run: npm publish --provenance --access public
        working-directory: ./example-circular-dependencies-2-marco
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish example-circular-dependencies-2-polo
        run: npm publish --provenance --access public
        working-directory: ./example-circular-dependencies-2-polo
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
